apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 5
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: daprwebapitemplateapigateway
        imagePullPolicy: Never #when using local images always use Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: ClusterIP
  selector:
    app: gateway
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8080
