apiVersion: apps/v1
kind: Deployment
metadata:
  name: redhat-deployment
  labels:
    app: redhat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redhat
  template:
    metadata:
      labels:
        app: redhat
    spec:
      containers:
        - name: redhat
          image: redhat/ubi8
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: gateway
        imagePullPolicy: Never #when using local images always use Never
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi1-deployment
  labels:
    app: api1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api1
  template:
    metadata:
      labels:
        app: api1
    spec:
      containers:
      - name: api1
        image: api1
        imagePullPolicy: Never #when using local images always use Never
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi2-deployment
  labels:
    app: api2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api2
  template:
    metadata:
      labels:
        app: api2
    spec:
      containers:
      - name: api2
        image: api2
        imagePullPolicy: Never #when using local images always use Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: ClusterIP
  selector:
    app: gateway
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api1-service
spec:
  type: ClusterIP
  selector:
    app: api1
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api2-service
spec:
  type: ClusterIP
  selector:
    app: api2
  ports:
  - protocol: TCP
    port: 8083
    targetPort: 8080